Vagrant.configure("2") do |config|
        config.vm.box = "ubuntu_aws"
        config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
        config.vm.synced_folder "../.", "/vagrant", id: "vagrant-root"

        config.vm.provision "shell",
            inline: "wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb && sudo dpkg -i puppetlabs-release-precise.deb && sudo apt-get update && sudo apt-get -y install puppet"

        config.vm.provider :aws do |aws, override|
                aws.access_key_id = ACCESS_KEY
                aws.secret_access_key = SECRET_ACCESS_KEY
                aws.keypair_name = "development"
                override.ssh.private_key_path = "development.pem"
                aws.instance_type = "t1.micro"
                aws.security_groups = "default"
                aws.ami = "ami-a73264ce"
                override.ssh.username = "ubuntu"
        end

        config.vm.provision :puppet do |puppet|
                puppet.module_path = "modules"
                puppet.manifests_path = "manifests"
                puppet.manifest_file = "init.pp"
        end
end